site_name: ftm-lakehouse
site_url: https://openaleph.org/docs/lib/ftm-lakehouse
repo_url: https://github.com/openaleph/ftm-lakehouse
nav:
  - Intro: index.md
  - quickstart.md
  - usage.md
  - RFC: rfc.md
  - functionality.md
  - architecture.md
  - Detailed Usage:
    - Working with Entities: usage/entities.md
    - Working with Files: usage/archive.md
    - Working with Mappings: usage/mappings.md
    - CLI Reference: usage/cli.md
  - Deployment:
    - Configuration: deployment/configuration.md
    - REST API: deployment/api.md
    - ZFS Integration: deployment/zfs.md
  - Reference:
    - ftm_lakehouse.lake: reference/lake.md
    - ftm_lakehouse.core: reference/core.md
    - ftm_lakehouse.model: reference/model.md
    - ftm_lakehouse.storage: reference/storage.md
    - ftm_lakehouse.repository: reference/repository.md
    - ftm_lakehouse.operation: reference/operation.md
    - ftm_lakehouse.logic: reference/logic.md
theme:
  name: material
  logo: https://cdn.investigativedata.org/style/logos/darc/svg/DARC-Logo-RGB-Horizontal-Neg.svg
  favicon: https://cdn.investigativedata.org/style/logos/darc/favicon.ico
  custom_dir: docs/overrides
  palette:
    - media: "(prefers-color-scheme)"
      scheme: slate
      toggle:
        icon: lucide/sun
        name: Switch to light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      toggle:
        icon: lucide/moon
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: lucide/sun
        name: Switch to light mode
  features:
    - navigation.instant
    - navigation.tracking
    - navigation.sections
    - toc.follow
    - content.code.copy
extra_css:
  - https://dataresearchcenter.github.io/zensical-theme-darc/stylesheets/darc-zensical.css
extra:
  logo_light: https://cdn.investigativedata.org/style/logos/darc/svg/DARC-Logo-RGB-Horizontal-Pos.svg
  social:
    - icon: lucide/mail
      link: mailto:hi@dataresearchcenter.org
    - icon: lucide/globe
      link: https://dataresearchcenter.org
    - icon: simple/github
      link: https://github.com/openaleph/ftm-lakehouse
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/company/dataresearchcenter/
markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.details
  - admonition
  - pymdownx.tasklist:
      custom_checkbox: true
plugins:
  - search
  - autorefs
  - mkdocs-typer2:
      pretty: true
  - mkdocstrings:
      default_handler: python
      handlers:
        python:
          options:
            docstring_style: google
            show_root_heading: false
            show_object_full_path: false
