# ---------------------------------------------------------------------------
# https://putf.sh/reference/auth/
# ---------------------------------------------------------------------------
map "$http_x_api_key:$http_x_api_secret" $key_ok {
    default                            0;
    "test-key:test-secret"             1;
}

map "$http_x_api_key:$request_method:$uri" $auth_ok {
    default                                        0;
    "~^test-key:[^:]+:/"                           1;
}

map "$uri:$key_ok:$auth_ok" $deny {
    default          1;
    "~:1:1$"         0;
}
